### ISSUE TITLE
Cannot execute on windows 7

### ISSUE THREAD

**Issue by IVREI0T** [rogerta97/Project2_Zelda#1]
# Issue Title : 
Cannot execute on windows 7
# Priority Level 
(A = Severe, crash; B = important, affects gameplay; C = cosmetic, polish) :
B
## Expected behavior :

Normal behaviour

## Actual behavior :

![image](https://cloud.githubusercontent.com/assets/17142213/23622773/3ec2f5b4-02a0-11e7-9508-0b8a4ebea438.png)

## Steps to reproduce :

Execute on windows 7

**Comment by Trodek** [comment]
Solved at v0.4
