### ISSUE TITLE
2 - Unlimited ulti

### ISSUE THREAD

**Issue by GuillemD** [rogerta97/Project2_Zelda#19]
#Issue Title : Two Links with nonstop ulti

#Priority Level 
(A = Severe, crash; B = important, affects gameplay; C = cosmetic, polish) : B

##Expected behavior :
When two Links use ulti, they shoudl go through each other and finish the ability.

##Actual behavior :
They get stuck, running at each other infinitely.

##Steps to reproduce :

Start game, pick 2 Links in different teams, face each other and use ulti.

**Comment by Guillemsc** [comment]
I think it's solved but needs to be tried.

**Comment by GuillemD** [comment]
To try: tuesday at class with 2 and more controllers
