### ISSUE TITLE
Non-Walkable Area Is Accessible! 

### ISSUE THREAD

**Issue by rogerta97** [rogerta97/Project2_Zelda#26]
#Issue Title: Non-Walkable Area Is Accessible! 

#Priority Level: B

##Expected behavior: The player should never be able to go beyond the map limits.

##Actual behavior: You actually can go trough one wall and walk trough non-walkable areas.  

##Steps to reproduce: At the moment of starting the main scene go right even before than the screen draws, sometimes the player will be able to cross the wall next to him.

**Comment by IVREI0T** [comment]
Duplicate of #51
