### ISSUE TITLE
Minion crash when colliding with ally

### ISSUE THREAD

**Issue by GuillemD** [rogerta97/Project2_Zelda#35]
#Issue Title : Minion crash when colliding with ally

#Priority Level 
(A = Severe, crash; B = important, affects gameplay; C = cosmetic, polish) : A

##Expected behavior :

Players should be able to hit your own minions without any consequences.

##Actual behavior :
When a player collides with a minion of its own team, game crashes

##Steps to reproduce :
Start game, when minions spawn, collide with your own minions

**Comment by Guillemsc** [comment]
This should be closed?
