### ISSUE TITLE
Game crashes if the game is open for a while at the menu

### ISSUE THREAD

**Issue by SimonStoyanov** [rogerta97/Project2_Zelda#62]
# Issue Title : 
Game crashes if the game is open for a while
# Priority Level 
A = Severe, crash

## Expected behavior :
Sholdn't crash at the menu

## Actual behavior :
Crashes with time

## Steps to reproduce :
do nothing at the main menu

**Comment by IVREI0T** [comment]
Unable to reproduce. Can you tell us how much time was spent in the main menu?

**Comment by sergipa** [comment]
Cannot reproduce
