### ISSUE TITLE
Ganon's jump bigger than expected

### ISSUE THREAD

**Issue by JosepContact** [rogerta97/Project2_Zelda#64]
# Issue Title : 
Ganon's jump bigger than expected
# Priority Level 
(A = Severe, crash; B = important, affects gameplay; C = cosmetic, polish) :
B
## Expected behavior :
Ganon jumps as much as the area shows before using the ability.

## Actual behavior :
Ganon jumps as much as the area shows before using the abilityway further.

## Steps to reproduce :

Use Ganon's ability

**Comment by IVREI0T** [comment]
Checked it, this is working as intended.
