### ISSUE TITLE
A Game Crash

### ISSUE THREAD

**Issue by sergipa** [rogerta97/Project2_Zelda#65]
# Issue Title : 

# Priority Level 
(A = Severe, crash; B = important, affects gameplay; C = cosmetic, polish) :

## Expected behavior :
Not crash

## Actual behavior :

It crashes

## Steps to reproduce :
 When you do quick start and all navis are in the same spot and one dies

**Comment by IVREI0T** [comment]
Poorly described, unable to reproduce
