### ISSUE TITLE
A Game freeze

### ISSUE THREAD

**Issue by sergipa** [rogerta97/Project2_Zelda#67]
# Issue Title : 
The game freezes
# Priority Level 
(A = Severe, crash; B = important, affects gameplay; C = cosmetic, polish) :
A
## Expected behavior :
Not freeze

## Actual behavior :
It freezes

## Steps to reproduce :
We were killing ganon while he was jumping and he was in the middle of a wall

**Comment by IVREI0T** [comment]
Replicate from #61
