### ISSUE TITLE
Blocked tower sprite not showing correctly

### ISSUE THREAD

**Issue by IVREI0T** [rogerta97/Project2_Zelda#74]
# Issue Title : 

# Priority Level 
(A = Severe, crash; B = important, affects gameplay; C = cosmetic, polish) : C

## Expected behavior :

When a blocked tower attacks, it should have the same color

## Actual behavior :

Blocked towers attack as if they were active, which looks weird

## Steps to reproduce :

get attacked by an unkillable tower

**Comment by IVREI0T** [comment]
Decided not to fix for the Alpha

**Comment by GuillemD** [comment]
fixed
