### ISSUE TITLE
Weird crash

### ISSUE THREAD

**Issue by IVREI0T** [rogerta97/Project2_Zelda#75]
# Issue Title : 

# Priority Level 
(A = Severe, crash; B = important, affects gameplay; C = cosmetic, polish) : A

## Expected behavior :

???

## Actual behavior :

Crash

## Steps to reproduce :

Pressed X and B at the same time while a quest was active, this happened once but we're unable to reproduce it.

**Comment by sergipa** [comment]
Cannot reproduce
