### ISSUE TITLE
Remap sould be more visual when looking at the controls

### ISSUE THREAD

**Issue by SimonStoyanov** [rogerta97/Project2_Zelda#78]
# Priority Level 
C = cosmetic, polish

## Expected behavior :
The controls should be corrected if they are remapped

## Actual behavior :
The controls are the default ones even though they were changed.
The controls should be individual to the player also.

## Steps to reproduce :
Change the controls

**Comment by sergipa** [comment]
We assume that if you use the remapping option you've played the game before, we won't change it.
